### ISSUE TITLE
calendar component not working

### ISSUE THREAD

**Issue by jschwalbe** [torkildr/appdaemon-conf#1]
Hello,

I've replicated all your files (custom_widgets/calendar.yaml, custom_widgets/basecalendar/*, apps/ical.yaml, apps/ical.py, assets/javascript/*), and added a google calendar .ics URL to the ical.yaml file. I've edited the dashboard file. 

I'm unable to get it to display calendar events. Error as below.  Is there anything obvious I'm missing? Thanks!

```
2018-04-26 23:01:05.275415 WARNING AppDaemon: ------------------------------------------------------------
2018-04-26 23:01:05.275579 WARNING AppDaemon: Unexpected error in worker for App google_calendar:
2018-04-26 23:01:05.275754 WARNING AppDaemon: Worker Ags: {'name': 'google_calendar', 'id': UUID('<snip>'), 'type': 'timer', 'function': <bound method Calendar.updateState of <ical.Calendar object at 0x1047bea20>>, 'kwargs': {'interval': 60}}
2018-04-26 23:01:05.275867 WARNING AppDaemon: ------------------------------------------------------------
2018-04-26 23:01:05.276190 WARNING AppDaemon: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 527, in worker
    funcref(self.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/Users/ob1/.homeassistant/conf/apps/ical.py", line 50, in updateState
    self.set_app_state(self.entity, state="", attributes=events)
AttributeError: 'Calendar' object has no attribute 'set_app_state'
```
Current version:
```
$ appdaemon -v
appdaemon 3.0.1
```

**Comment by torkildr** [comment]
As far as I can tell, you're doing everything correctly.

Not that it necessarily has anything to do with it, but have you pip installed the `ics` module?

**Comment by jschwalbe** [comment]
Yes, I’ve installed ics via pip.
Are there any extra files that might be missing? Or any way to get more detailed errors?

**Comment by jschwalbe** [comment]
@renetode any ideas?

**Comment by jschwalbe** [comment]
I busted thru the first error by adding a few extra files (including a javascript file - moment.min.js).

Here's the current javascript error:
```
Uncaught TypeError: Cannot read property 'map' of undefined
    at Object.self.onData (application.js:2519)
    at Object.success (dashboard.js:194)
    at i (jquery-3.1.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.1.1.min.js:2)
    at A (jquery-3.1.1.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-3.1.1.min.js:4)
```

Seems like it's trying to use the map function from the above min js file, which (I think) is loading correctly. Any ideas?

**Comment by jschwalbe** [comment]
At least part of my problem was solved by adding an event to my calendar. I created a new calendar just for testing and the event had occurred yesterday. Moving it to tomorrow yielded nice results. Now trying to figure out how to make Apple's iCal work. 
This can be closed.

**Comment by torkildr** [comment]
Sounds weird that the python should crash when missing some javascript.

Also sounds bad that no data fails in the way it does.

Great to hear you got it working 👍
